# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Game(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, title: str=None, description: str=None, price: float=None):  # noqa: E501
        """Game - a model defined in Swagger

        :param id: The id of this Game.  # noqa: E501
        :type id: int
        :param title: The title of this Game.  # noqa: E501
        :type title: str
        :param description: The description of this Game.  # noqa: E501
        :type description: str
        :param price: The price of this Game.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {
            'id': int,
            'title': str,
            'description': str,
            'price': float
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'description': 'description',
            'price': 'price'
        }
        self._id = id
        self._title = title
        self._description = description
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'Game':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Game of this Game.  # noqa: E501
        :rtype: Game
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Game.


        :return: The id of this Game.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Game.


        :param id: The id of this Game.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Game.


        :return: The title of this Game.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Game.


        :param title: The title of this Game.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this Game.


        :return: The description of this Game.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Game.


        :param description: The description of this Game.
        :type description: str
        """

        self._description = description

    @property
    def price(self) -> float:
        """Gets the price of this Game.


        :return: The price of this Game.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Game.


        :param price: The price of this Game.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price
